name: paradrop
version: 3
summary: Routers
description: Routers and Virtualization
confinement: strict
vendor: ParadropLabs <pd@paradrop.org>
icon: ./icon.png

services:
  sev:
    start: ./bin/core
    description: "Paradrop Daemon"
    caps:
      - network-client
      - network-service
      - network-admin

parts:
  core:
    plugin: go
    source: core
    build-packages:
      - python-dev
    stage-packages:
      - python-dev

  paradrop:
    plugin: python2
    source: python
