name: paradrop
version: 3
summary: Routers
description: Routers and Virtualization
confinement: strict
vendor: ParadropLabs <pd@paradrop.org>
icon: ./icon.png

services:
  paradrop:
    start: ./bin/core
    description: "Paradrop Daemon"
    caps:
      - network-client
      - network-service
      - network-admin

parts:
  paradrop:
    plugin: python2
    source: src

  paradrop-run-script:
    plugin: copy
    source: src
    files:
      run: bin/run

  # core:
  #   plugin: go
  #   source: core
  #   build-packages:
  #     - python-dev
  #   stage-packages:
  #     - python-dev

