name: paradrop
version: 3
summary: Routers
description: Routers and Virtualization
confinement: devmode
vendor: ParadropLabs <pd@paradrop.org>
icon: ./icon.png

services:
  paradrop:
    start: runpd
    description: "Paradrop Daemon"
    caps:
      - network-client
      - network-service
      - network-admin
      - network-control
      - network-observe

parts:
  paradrop:
    plugin: python2
    source: src

  assets:
    plugin: copy
    files:
      src/runpd: runpd
    after:
      - paradrop
