name: paradrop
version: 3
summary: Routers
description: Routers and Virtualization
confinement: devmode
vendor: ParadropLabs <pd@paradrop.org>
icon: ./icon.png

services:
  paradrop:
    start: bin/pd
    description: "Paradrop Daemon"
    caps:
      - network-client
      - network-service
      - network-admin

parts:
  paradrop:
    plugin: python2
    source: src

  assets:
    plugin: copy
    files:
      src/pd: bin/pd
